### ISSUE TITLE
Files from /locust share does not get used

### ISSUE THREAD

**Issue by dabedin** [yorek/locust-on-azure#1]
While attempting to change the behavior of azure-deploy.sh to upload a directory (my test upload a file via post) It seemed my edited locustfile.py did not get used: regardless of my test being a POST, a fresh deployment of Locust continued to report GET /customer/[id] as 100% of failures, as my host does not support GET.
My edited locustfile.py and additional file is in the Storage Files share, connecting to a slave ACI I can see the mounted /locust share, in which my files listed, and a default locustfile.py is present too. 
![locust_aci](https://user-images.githubusercontent.com/11557301/76448482-b1750000-63ca-11ea-90a9-9325359e5f60.png)
How can I configure the master&slaves to use the files in the /locust dir instead of the locustfile.py coming from the docker image? Any hint would be appreciated

**Comment by yorek** [comment]
Hi @dabedin thanks for reporting this, it looks like locust is always using the locustfile.py included in the image...which should not be there at all. By default locust use the `locustfile.py`, and it also seems that the ARM template mount the folder so that the `locustfile.py` available in Azure Blob is monted in the locust folder and not in the root one. Will fix these issues ASAP, thanks.

**Comment by yorek** [comment]
Released fix, and also changed existing locustfile.py to use both GET and POST and the JSONPlaceholder test service. Let me know if it work as expected now.

**Comment by dabedin** [comment]
Thanks @yorek! It now works as expected.
_Not an issue in your repo, thanks in advance for your help_ I am having a hard time understanding the context locust is working on: in my locustfile.py I open another file which I uploaded along with it to the File Share
```
class APICalls(TaskSet):    
    @task()
    def analyzeimage(self):
        image = open('/locust/sample_face.png', 'rb')
        self.client.post("", files={"shot": image}, name="/posts")
```
![locust_aci](https://user-images.githubusercontent.com/11557301/76514579-66093300-6458-11ea-87d9-0227ff4e8773.png)

I tried with the /locust path (and many other attempts) but I get errors along

> [2020-03-12 09:30:55,163] wk-caas------/ERROR/locust.core: [Errno 2] No such file or directory: 'sample_face.png'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/locust/core.py", line 400, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.7/site-packages/locust/core.py", line 430, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/usr/local/lib/python3.7/site-packages/locust/core.py", line 442, in execute_task
    task(self, *args, **kwargs)
  File "/locust/locustfile.py", line 8, in analyzeimage
    image = open('/locust/sample_face.png', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'sample_face.png'

**Comment by yorek** [comment]
I cannot help on this, as I never had this need, but this article can help you maybe: 

https://thispointer.com/python-how-to-get-the-current-working-directory/

**Comment by dabedin** [comment]
It was just a transient error, the code above was ok. All is fine from the automation PoV, the slaves seems to drop communication with the master sometime but this is a Locust thing
